### ISSUE TITLE
亚马逊服务器安装CRON失败

### ISSUE THREAD

**Issue by weichanglin0010** [fscarmen/unlock_warp#1]
脚本版本: 1.13  功能新增: Wireguard-go-reserved 支持更换 IP
 
======================================================================================================================

 
 1. 模式1: 定时5分钟检查一次,遇到不解锁时更换 WARP IP，直至刷成功
 2. 模式2: 创建 systemd 服务。进程一直在后台，当刷成功后，每隔1小时检查一次
 3. 模式3: 用 nohup 创建一个 jobs。进程一直在后台，当刷成功后，每隔1小时检查一次
 4. 模式4: 创建一个名为 [u] 的 Screen 会话。进程一直在后台，当刷成功后，每隔1小时检查一次
 5. 模式5: 安装 pm2 守护进程，安装依赖需较长时间。进程一直在后台，当刷成功后，每隔1小时检查一次
 6. 卸载
 0. 退出
 
 请选择: 1
 安装 cron 中…… 
Last metadata expiration check: 1 day, 2:11:58 ago on Sun 17 Sep 2023 11:28:20 AM CST.
No match for argument: cron
 先升级软件库才能继续安装 cron，时间较长，请耐心等待…… 
Last metadata expiration check: 1 day, 2:11:58 ago on Sun 17 Sep 2023 11:28:20 AM CST.
=====================================================================================================================================================================
WARNING:
  A newer release of "Amazon Linux" is available.

  Available Versions:

  Version 2023.1.20230825:
    Run the following command to upgrade to 2023.1.20230825:

      dnf upgrade --releasever=2023.1.20230825

    Release notes:
     https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230825.html

  Version 2023.1.20230906:
    Run the following command to upgrade to 2023.1.20230906:

      dnf upgrade --releasever=2023.1.20230906

    Release notes:
     https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230906.html

  Version 2023.1.20230912:
    Run the following command to upgrade to 2023.1.20230912:

      dnf upgrade --releasever=2023.1.20230912

    Release notes:
     https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html

=====================================================================================================================================================================
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 1 day, 2:11:59 ago on Sun 17 Sep 2023 11:28:20 AM CST.
No match for argument: cron
 安装 cron 失败，脚本中止，问题反馈:[https://github.com/fscarmen/unlock_warp/issues]

**Comment by JAVFLIX** [comment]
美国服务器表示同样失败

**Comment by fscarmen** [comment]
> 美国服务器表示同样失败

什么系统和版本？

**Comment by JAVFLIX** [comment]
> > 美国服务器表示同样失败
> 
> 什么系统和版本？

centos7.9

**Comment by JAVFLIX** [comment]
我换成Ubuntu22正常了🤣

**Comment by fscarmen** [comment]
> > > 美国服务器表示同样失败
> > 
> > 
> > 什么系统和版本？
> 
> centos7.9

正想和你借个系统来试试的

**Comment by fscarmen** [comment]
> 脚本版本: 1.13 功能新增: Wireguard-go-reserved 支持更换 IP
> 
> ======================================================================================================================
> 
> 1. 模式1: 定时5分钟检查一次,遇到不解锁时更换 WARP IP，直至刷成功
> 2. 模式2: 创建 systemd 服务。进程一直在后台，当刷成功后，每隔1小时检查一次
> 3. 模式3: 用 nohup 创建一个 jobs。进程一直在后台，当刷成功后，每隔1小时检查一次
> 4. 模式4: 创建一个名为 [u] 的 Screen 会话。进程一直在后台，当刷成功后，每隔1小时检查一次
> 5. 模式5: 安装 pm2 守护进程，安装依赖需较长时间。进程一直在后台，当刷成功后，每隔1小时检查一次
> 6. 卸载
> 7. 退出
> 
> # 请选择: 1
> 安装 cron 中……
> Last metadata expiration check: 1 day, 2:11:58 ago on Sun 17 Sep 2023 11:28:20 AM CST.
> No match for argument: cron
> 先升级软件库才能继续安装 cron，时间较长，请耐心等待……
> Last metadata expiration check: 1 day, 2:11:58 ago on Sun 17 Sep 2023 11:28:20 AM CST.
> WARNING: A newer release of "Amazon Linux" is available.
> 
> Available Versions:
> 
> Version 2023.1.20230825: Run the following command to upgrade to 2023.1.20230825:
> 
> ```
>   dnf upgrade --releasever=2023.1.20230825
> 
> Release notes:
>  https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230825.html
> ```
> 
> Version 2023.1.20230906: Run the following command to upgrade to 2023.1.20230906:
> 
> ```
>   dnf upgrade --releasever=2023.1.20230906
> 
> Release notes:
>  https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes-2023.1.20230906.html
> ```
> 
> Version 2023.1.20230912: Run the following command to upgrade to 2023.1.20230912:
> 
> ```
>   dnf upgrade --releasever=2023.1.20230912
> 
> Release notes:
>  https://docs.aws.amazon.com/linux/al2023/release-notes/relnotes.html
> ```
> 
> ===================================================================================================================================================================== Dependencies resolved. Nothing to do. Complete! Last metadata expiration check: 1 day, 2:11:59 ago on Sun 17 Sep 2023 11:28:20 AM CST. No match for argument: cron 安装 cron 失败，脚本中止，问题反馈:[https://github.com/fscarmen/unlock_warp/issues]

你google和chatGPT查查该系统如何安装crontab，由于这些系统我极少测试，可能安装依赖的包名错了。

**Comment by JAVFLIX** [comment]
> > > > 美国服务器表示同样失败
> > > 
> > > 
> > > 什么系统和版本？
> > 
> > 
> > centos7.9
> 
> 正想和你借个系统来试试的

服务器多的是，192.210.xxx.9 root SFz**********hwe

**Comment by fscarmen** [comment]
好，要中午试下

longgege666 ***@***.***>于2023年11月18日 周六08:34写道：

**Comment by fscarmen** [comment]
> > > > > 美国服务器表示同样失败
> > > > 
> > > > 
> > > > 什么系统和版本？
> > > 
> > > 
> > > centos7.9
> > 
> > 
> > 正想和你借个系统来试试的
> 
> 服务器多的是，192.210.xxx.9 root SFz**********hwe

已经处理了，更新了脚本，测试正常了

<img width="716" alt="image" src="https://github.com/fscarmen/unlock_warp/assets/62703343/2057e536-482e-4cae-a9d0-061ea7c586c6">

**Comment by fscarmen** [comment]
> 
> ===================================================================================================================================================================== Dependencies resolved. Nothing to do. Complete! Last metadata expiration check: 1 day, 2:11:59 ago on Sun 17 Sep 2023 11:28:20 AM CST. No match for argument: cron 安装 cron 失败，脚本中止，问题反馈:[https://github.com/fscarmen/unlock_warp/issues]

更新了脚本，你也试试是否 OK.

**Comment by JAVFLIX** [comment]
牛的

> > > > > > 美国服务器表示同样失败
> > > > > 
> > > > > 
> > > > > 什么系统和版本？
> > > > 
> > > > 
> > > > centos7.9
> > > 
> > > 
> > > 正想和你借个系统来试试的
> > 
> > 
> > 服务器多的是，192.210.xxx.9 root SFz**********hwe
> 
> 已经处理了，更新了脚本，测试正常了
> 
> <img alt="image" width="716" src="https://user-images.githubusercontent.com/62703343/283996292-2057e536-482e-4cae-a9d0-061ea7c586c6.png">

牛的
