### ISSUE TITLE
A typo found in the warp_unlock.sh script.

### ISSUE THREAD

**Issue by KipRire** [fscarmen/unlock_warp#6]
Hi, Thanks for you great job!

One of my ipv6 only (HK) machine cannot "brush ip" and do "warp_restart" correctly while I'm using the bash script `warp_unlock.sh`.  Then I run `bash /usr/bin/warp_unlock.sh` directly and got a "register error". 

After checking the code of `warp_unlock.sh` and `api.sh`, I found a typo in **line 436** of [warp_unlock.sh](https://gitlab.com/fscarmen/warp_unlock/-/blob/main/unlock.sh?ref_type=heads). It should be `--register` rather than `--registe` missing a "r".

I solved my problem by correcting it. 
Thanks to you again!

**Comment by fscarmen** [comment]
Ths.I will fix today.

**Comment by fscarmen** [comment]
Fixed: https://gitlab.com/fscarmen/warp_unlock/-/commit/6617a25d2a489f97529c0445dd3a2dac1a9b85df#585052509b9b309166ee778d6ab2bc181bf3a03e_437_443

<img width="831" alt="image" src="https://github.com/fscarmen/unlock_warp/assets/62703343/52be6de3-c689-4cf2-9633-d46b053ef064">
