### ISSUE TITLE
if [[ \$(pgrep -laf ^[/d]*bash.*warp_unlock | awk -F, '{a[\$2]++}END{for (i in a) print i" "a[i]}') -le 2 ]]; then 这句是不是有问题

### ISSUE THREAD

**Issue by farquer** [fscarmen/unlock_warp#7]
`if [[ \$(pgrep -laf ^[/d]*bash.*warp_unlock | awk -F, '{a[\$2]++}END{for (i in a) print i" "a[i]}') -le 2 ]]; then`

有点没看懂，如果想确认是不是有在执行的 | wc -l 就可以吧，为什么这么复杂

我感觉我的脚本一直进不到这个if里面，一直没有执行check

使用的 docker

**Comment by fscarmen** [comment]
这个的确是可以用 wc -l 简单的替代，这样写的目的是为了尽量减少依赖，以防有的系统没有 wc 指令，这样又要在 查依赖的时候多查 wc 。
整个脚本包括兄弟脚本，我的主体思路是依赖越少越好，比如 cut 指令，我都是用 awk -F 来统一替代的。

这个是自锁判断来的，即是已经有解锁脚本在运行中，再次运行的话，会因为进程数限制而让新的马上退出，让旧的继续执行。

你说没有进到这个 if 里面，你可以查查 是否已经在运行解锁脚本了。

PS，查了一下，这句是最早一条 commit 已经是这样写了，厉害：）

<img width="1680" alt="image" src="https://github.com/fscarmen/unlock_warp/assets/62703343/fc12e732-0210-484f-8afe-030bf9275f6a">

**Comment by fscarmen** [comment]
不过以现在的理解来看，的确可以用更简单的处理 
`if pgrep -laf warp_unlock >/dev/null 2>&1; then`
或
`if [[ $(ps -ef | grep -c warp_unlock) > 1 ]]; then`

，2年前代码水平比现在差多了。

**Comment by fscarmen3** [comment]
我改了这句老古董了。
<img width="1307" alt="image" src="https://github.com/fscarmen/unlock_warp/assets/116377995/aa7a2e19-5c70-44f4-80b9-3a3da26aa4cb">

**Comment by fscarmen** [comment]
我改了这句老古董了。
<img width="1307" alt="image" src="https://github.com/fscarmen/unlock_warp/assets/116377995/aa7a2e19-5c70-44f4-80b9-3a3da26aa4cb">

**Comment by farquer** [comment]
这样确实清晰多了  👍 ，但是没太懂 < 4 的原因

**Comment by fscarmen** [comment]
我也搞不懂，我开头觉得3是可以了，但测试了，是一样用crontab 模拟的，发现3不行，要4，我也搞不清为什么，你看看运行有没问题？

**Comment by fscarmen3** [comment]
# < 3 时，会退出
<img width="1005" alt="image" src="https://github.com/fscarmen/unlock_warp/assets/116377995/c9f5716c-dc8d-4851-bdbc-6bde7d559b5f">

# < 4 时，会正常
![image](https://github.com/fscarmen/unlock_warp/assets/116377995/b22959f2-3c34-4214-884e-e4293e06ee79)

**Comment by fscarmen** [comment]
我做也个监测的来看进程，我仍然搞不明白为什么 < 3 不行，但结果就是这样，我唯一想到的就是定时任务运行时，瞬间还有一条进程，所以是3条，但这个极短，很难捕捉到。
```
while true; do pgrep -laf warp_unlock; sleep 5; done
```

## < 3 时，会退出
<img width="1005" alt="image" src="https://github.com/fscarmen/unlock_warp/assets/116377995/c9f5716c-dc8d-4851-bdbc-6bde7d559b5f">

## < 4 时，会正常
![image](https://github.com/fscarmen/unlock_warp/assets/116377995/b22959f2-3c34-4214-884e-e4293e06ee79)
